# Generated by Django 6.1.1 on 2026-09-28 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAlimentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.CharField(blank=True, default='', max_length=500)),
                ('nome', models.CharField(max_length=120)),
                ('objetivo', models.CharField(choices=[('hipertrofia', 'Hipertrofia'), ('emagrecimento', 'Emagrecimento'), ('forca', 'Força'), ('condicionamento', 'Condicionamento')], max_length=20)),
                ('calorias_dia', models.PositiveIntegerField()),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.CharField(blank=True, default='', max_length=500)),
                ('nome', models.CharField(max_length=120)),
                ('objetivo', models.CharField(choices=[('hipertrofia', 'Hipertrofia'), ('emagrecimento', 'Emagrecimento'), ('forca', 'Força'), ('condicionamento', 'Condicionamento')], max_length=20)),
                ('nivel', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], max_length=15)),
                ('duracao_semanas', models.PositiveSmallIntegerField(default=8)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('plano_sugerido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas', to='app.planoalimentar')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(help_text='Número do treino (1 = Treino A, 2 = Treino B...)')),
                ('exercicio', models.CharField(max_length=120)),
                ('series', models.PositiveSmallIntegerField()),
                ('repeticoes', models.CharField(help_text='Ex.: 8-12', max_length=20)),
                ('descanso_seg', models.PositiveSmallIntegerField(default=60)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.programatreino')),
            ],
            options={
                'ordering': ['dia', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cafe', 'Café da manhã'), ('lanche', 'Lanche'), ('almoco', 'Almoço'), ('jantar', 'Jantar'), ('ceia', 'Ceia')], max_length=10)),
                ('descricao', models.CharField(max_length=250)),
                ('calorias', models.PositiveIntegerField()),
                ('proteina_g', models.PositiveIntegerField(default=0)),
                ('carbo_g', models.PositiveIntegerField(default=0)),
                ('gordura_g', models.PositiveIntegerField(default=0)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='app.planoalimentar')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
